---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-web-uuid
  namespace: web
  labels:
    app: simple-web-uuid
    app.kubernetes.io/component: simple-web-uuid
    app.kubernetes.io/instance: simple-web-uuid
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: simple-web-uuid
    app.kubernetes.io/part-of: web
spec:
  minReplicas: 3
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-web-uuid
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
